### ISSUE TITLE
Option to manually name downloaded file or remove special characters

### ISSUE THREAD

**Issue by tomzazo** [reujab/wallpaper#16]
To my understanding if you use `SetFromURL` , the `donwloadImage` function names the downloaded image as the last part of the URL path. Here is the issue with that. If you use a URL path with certain characters, the whole thing will crash, as some characters aren't allowed to be used as file name on Windows (not sure about other OSes). Would it make sense to add an option to allow manual naming of the downloaded image file? Or maybe just removing special characters from file name could also suffice?

**Comment by tomzazo** [comment]
Oops, this is relevant here: #15

**Comment by reujab** [comment]
Fixed by #15.
