### ISSUE TITLE
unable to use in linux

### ISSUE THREAD

**Issue by biij5698** [reujab/wallpaper#17]
when i run the example code in linux(deepin/ubuntu):
panic: exec: "dconf": executable file not found in $PATH

goroutine 1 [running]:
main.main()
	/home/lizi/space/gospace/test/wallpaper.go:13 +0xe5
exit status 2

**Comment by reujab** [comment]
`dconf` is a dependency for GNOME-based desktops. What's the output of `which dconf`?
