### ISSUE TITLE
Not working on manjaro XFCE

### ISSUE THREAD

**Issue by cauefcr** [reujab/wallpaper#7]
It just sets the default wallpaper.

I tried running the command the package uses in the command line and it didn't work either.

**Comment by reujab** [comment]
What do you mean by default wallpaper?

**Comment by cauefcr** [comment]
I mean the wallpaper that comes set when you install the OS

**Comment by reujab** [comment]
Does it happen with SetFromFile as well as SetFromURL?

**Comment by cauefcr** [comment]
I didn't test SetFromUrl.

**Comment by reujab** [comment]
Well if it didn't work for SetFromFile, it definitely won't work with SetFromURL. I'll test it on XFCE later today.

**Comment by reujab** [comment]
I couldn't reproduce your exact issue, but I fixed a panic with XFCE, so it should work now. Apologies for taking so long to fix it.
